name: Gradle Publish

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant necessary permission
      run: chmod +x gradlew
    - name: Publish to Repository
      run: ./gradlew publish
      env:
        ORG_GRADLE_PROJECT_repoUsername: ${{ secrets.REPO_USERNAME }}
        ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.REPO_PASSWORD }}
